VIDEO_PROCESSING_FAILED_TOPIC = "video.processing.failed"
VIDEO_READY_TOPIC = "video.ready"
VIDEO_UPLOADED_TOPIC = "video.uploaded"
VIDEO_VIEWED_TOPIC = "video.viewed"
LIVE_STARTED_TOPIC = "live.started"
LIVE_ENDED_TOPIC = "live.ended"

VIDEO_PROCESSING_STARTED_TOPIC = "video.processing.started"

# Backward-compatible aliases used by older consumers/modules.
VIDEO_READY = VIDEO_READY_TOPIC
VIDEO_UPLOADED = VIDEO_UPLOADED_TOPIC
VIDEO_PROCESSING_STARTED = VIDEO_PROCESSING_STARTED_TOPIC
VIDEO_PROCESSING_FAILED = VIDEO_PROCESSING_FAILED_TOPIC
VIDEO_VIEWED = VIDEO_VIEWED_TOPIC
LIVE_STARTED = LIVE_STARTED_TOPIC
LIVE_ENDED = LIVE_ENDED_TOPIC
