apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: video-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      enableServiceLinks: false

      containers:
        - name: api
          image: 9836sagar9836/video-api:v1

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret

          volumeMounts:
            - name: media-storage
              mountPath: /app/media

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

      volumes:
        - name: media-storage
          emptyDir: {}
