apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: video-platform
type: Opaque
stringData:
  JWT_SECRET: "super-secret-key"

  MAIL_USERNAME: "sagarpaal116@gmail.com"
  MAIL_PASSWORD: "yymu yesd nkhf tejw"

  AWS_ACCESS_KEY_ID: "YOUR_AWS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET"

  LIVEKIT_API_KEY: "devkey"
  LIVEKIT_API_SECRET: "1f221b798295dde71aa319ed2ca5b8615712d96e89fe5dc38c82f0333a6fe135"
