apiVersion: v1
kind: Service
metadata:
  name: livekit
  namespace: video-platform
spec:
  selector:
    app: livekit
  ports:
    - name: ws
      port: 7880
      targetPort: 7880

    - name: tcp
      port: 7881
      targetPort: 7881
