port: 7880

bind_addresses:
  - "0.0.0.0"

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: false
  node_ip: "172.23.58.167"

keys:
  devkey: "862176abb6dc458c91563e072725c6ff"

room:
  auto_create: true

logging:
  level: info
