port: 7880

bind_addresses:
  - "0.0.0.0"

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: false
  node_ip: "127.0.0.1"

redis:
  address: redis:6379

keys:
  devkey: 1f221b798295dde71aa319ed2ca5b8615712d96e89fe5dc38c82f0333a6fe135

room:
  auto_create: true

logging:
  level: info
